language: php

php:
    - 5.6
env:
  - NODE_VERSION="8.12.0"

before_script:
    - pecl install -f apcu-4.0.11  <<<''   
    - nvm install $NODE_VERSION
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --no-scripts

script:
    - vendor/bin/phpunit test --coverage-clover=coverage.xml   
    - composer run-script build-front-end
    
notifications:
  email: true
    
