language: php

php:
    - 5.6

before_script:
    - pecl install -f apcu-4.0.11  <<<''   
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --no-scripts

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml
    
notifications:
  email: false
    
