<?php
use Phinx\Migration\AbstractMigration;
class WordMeaningsData5 extends AbstractMigration {
    public function up() {
        $this->table('word_meanings')->insert([
array('word_id' => '862','n' => '1','meaning' => 'Empleado a sueldo'),
array('word_id' => '862','n' => '2','meaning' => 'Asalariado '),
array('word_id' => '863','n' => '1','meaning' => 'Palabra'),
array('word_id' => '863','n' => '2','meaning' => 'Lenguaje'),
array('word_id' => '863','n' => '3','meaning' => 'Idioma'),
array('word_id' => '864','n' => '1','meaning' => 'Precio (de bienes)'),
array('word_id' => '865','n' => '1','meaning' => 'Kimono'),
array('word_id' => '866','n' => '1','meaning' => 'Comienzo'),
array('word_id' => '867','n' => '1','meaning' => 'Fin'),
array('word_id' => '868','n' => '1','meaning' => 'El otro día'),
array('word_id' => '868','n' => '2','meaning' => 'Últimamente'),
array('word_id' => '869','n' => '1','meaning' => 'Cine '),
array('word_id' => '87','n' => '1','meaning' => 'Lo siento (informal) '),
array('word_id' => '870','n' => '1','meaning' => 'Servicio (Atención) '),
array('word_id' => '871','n' => '0','meaning' => 'Forma Informal'),
array('word_id' => '872','n' => '1','meaning' => 'Verbo'),
array('word_id' => '873','n' => '1','meaning' => 'Trazo (de kanji)'),
array('word_id' => '874','n' => '1','meaning' => 'Padres'),
array('word_id' => '875','n' => '1','meaning' => 'Naipe'),
array('word_id' => '875','n' => '2','meaning' => 'Carta (Juego) '),
array('word_id' => '877','n' => '1','meaning' => 'Viajar'),
array('word_id' => '877','n' => '2','meaning' => 'Hacer un viaje'),
array('word_id' => '878','n' => '1','meaning' => 'Llevar'),
array('word_id' => '878','n' => '2','meaning' => 'Transportar'),
array('word_id' => '878','n' => '3','meaning' => 'Actuar'),
array('word_id' => '878','n' => '4','meaning' => 'Celebrar'),
array('word_id' => '879','n' => '1','meaning' => 'Volver al país de origen'),
array('word_id' => '881','n' => '1','meaning' => 'Comida (alimentos)'),
array('word_id' => '882','n' => '1','meaning' => 'Cena (por la tarde)'),
array('word_id' => '883','n' => '1','meaning' => 'Bebida'),
array('word_id' => '884','n' => '1','meaning' => 'Ser visto'),
array('word_id' => '884','n' => '2','meaning' => 'Parecer'),
array('word_id' => '886','n' => '1','meaning' => 'Visita turística'),
array('word_id' => '886','n' => '2','meaning' => 'Turista'),
array('word_id' => '887','n' => '1','meaning' => 'Hacer turismo'),
array('word_id' => '889','n' => '1','meaning' => 'Educar'),
array('word_id' => '89','n' => '1','meaning' => 'Japonés (gentilicio)'),
array('word_id' => '890','n' => '0','meaning' => 'Enseñanza'),
array('word_id' => '890','n' => '1','meaning' => 'Educación (academíca)'),
array('word_id' => '891','n' => '1','meaning' => 'Iglesia'),
array('word_id' => '892','n' => '1','meaning' => 'Clase (lugar)'),
array('word_id' => '893','n' => '1','meaning' => 'Lectura'),
array('word_id' => '894','n' => '1','meaning' => 'Lector'),
array('word_id' => '895','n' => '1','meaning' => 'Caligrafía'),
array('word_id' => '896','n' => '1','meaning' => 'Tienda de libros'),
array('word_id' => '897','n' => '1','meaning' => 'Conversación'),
array('word_id' => '9','n' => '1','meaning' => 'Ahí '),
array('word_id' => '90','n' => '1','meaning' => 'España '),
array('word_id' => '901','n' => '1','meaning' => 'Petición'),
array('word_id' => '901','n' => '2','meaning' => 'Deseo'),
array('word_id' => '901','n' => '3','meaning' => 'Por favor (abreviado)'),
array('word_id' => '902','n' => '1','meaning' => 'Pedir un deseo'),
array('word_id' => '903','n' => '1','meaning' => 'Por favor (al pedir algo)'),
array('word_id' => '904','n' => '1','meaning' => 'Pensar'),
array('word_id' => '904','n' => '2','meaning' => 'Creer'),
array('word_id' => '904','n' => '3','meaning' => 'Opinar'),
array('word_id' => '905','n' => '1','meaning' => 'Decir'),
array('word_id' => '907','n' => '1','meaning' => 'Ganar (un partido)'),
array('word_id' => '908','n' => '1','meaning' => 'Perder (un partido)'),
array('word_id' => '908','n' => '2','meaning' => 'Ser derrotado'),
array('word_id' => '91','n' => '1','meaning' => 'Español (gentilicio)'),
array('word_id' => '910','n' => '1','meaning' => 'Evento '),
array('word_id' => '911','n' => '1','meaning' => 'Celebrar (un evento)'),
array('word_id' => '911','n' => '2','meaning' => 'Tener lugar (un evento) '),
array('word_id' => '912','n' => '1','meaning' => 'Ser útil'),
array('word_id' => '913','n' => '1','meaning' => 'Desperdiciar'),
array('word_id' => '913','n' => '2','meaning' => 'Malgastar'),
array('word_id' => '914','n' => '1','meaning' => 'Inconveniente'),
array('word_id' => '915','n' => '1','meaning' => 'Igual'),
array('word_id' => '915','n' => '2','meaning' => 'Mismo'),
array('word_id' => '915','n' => '3','meaning' => 'Equivalencia'),
array('word_id' => '916','n' => '1','meaning' => 'Maravilloso (expresión) '),
array('word_id' => '917','n' => '1','meaning' => 'Primer ministro'),
array('word_id' => '917','n' => '2','meaning' => 'Presidente de gobierno'),
array('word_id' => '919','n' => '1','meaning' => 'Presidente de un país'),
array('word_id' => '919','n' => '2','meaning' => 'Jefe de estado'),
array('word_id' => '92','n' => '1','meaning' => 'EEUU '),
array('word_id' => '920','n' => '1','meaning' => 'Política'),
array('word_id' => '921','n' => '1','meaning' => 'Noticia '),
array('word_id' => '922','n' => '1','meaning' => 'Discurso'),
array('word_id' => '922','n' => '2','meaning' => 'Charla '),
array('word_id' => '923','n' => '0','meaning' => 'Partido (deportes)'),
array('word_id' => '924','n' => '1','meaning' => 'Trabajo eventual '),
array('word_id' => '925','n' => '1','meaning' => 'Opinión'),
array('word_id' => '926','n' => '1','meaning' => 'Discurso'),
array('word_id' => '926','n' => '2','meaning' => 'Cuento'),
array('word_id' => '926','n' => '3','meaning' => 'Tema (conversación)'),
array('word_id' => '927','n' => '1','meaning' => 'Pronunciar un discurso '),
array('word_id' => '928','n' => '1','meaning' => 'Hablar sobre algo'),
array('word_id' => '929','n' => '1','meaning' => 'Sentido del humor '),
array('word_id' => '93','n' => '1','meaning' => 'Estadounidense'),
array('word_id' => '93','n' => '2','meaning' => 'Norteamericano'),
array('word_id' => '93','n' => '3','meaning' => 'Americano'),
array('word_id' => '930','n' => '1','meaning' => 'Tener sentido del humor'),
array('word_id' => '931','n' => '1','meaning' => 'Micrófono '),
array('word_id' => '932','n' => '1','meaning' => 'Diseño '),
array('word_id' => '933','n' => '1','meaning' => 'Transporte '),
array('word_id' => '933','n' => '2','meaning' => 'Tráfico'),
array('word_id' => '934','n' => '1','meaning' => 'Hora Punta '),
array('word_id' => '935','n' => '1','meaning' => 'Seguro (alta probabilidad)'),
array('word_id' => '935','n' => '2','meaning' => 'Cierto  '),
array('word_id' => '936','n' => '1','meaning' => 'Quizás'),
array('word_id' => '936','n' => '2','meaning' => 'Probablemente'),
array('word_id' => '937','n' => '1','meaning' => 'Canguro '),
array('word_id' => '938','n' => '0','meaning' => 'Últimamente'),
array('word_id' => '938','n' => '1','meaning' => 'Recientemente'),
array('word_id' => '938','n' => '2','meaning' => 'En la actualidad'),
array('word_id' => '939','n' => '1','meaning' => 'Realmente'),
array('word_id' => '939','n' => '2','meaning' => 'De verdad'),
array('word_id' => '94','n' => '1','meaning' => 'Diseñador (profesión) '),
array('word_id' => '940','n' => '1','meaning' => 'No tan (en frases negativas)'),
array('word_id' => '941','n' => '1','meaning' => 'Ir de compras'),
array('word_id' => '942','n' => '1','meaning' => 'Ser suficiente'),
array('word_id' => '943','n' => '1','meaning' => 'Por supuesto'),
array('word_id' => '944','n' => '1','meaning' => 'De hecho'),
array('word_id' => '944','n' => '2','meaning' => 'Para ser sincero'),
array('word_id' => '945','n' => '1','meaning' => 'Despacio  '),
array('word_id' => '946','n' => '1','meaning' => 'Gradualmente'),
array('word_id' => '946','n' => '2','meaning' => 'Pronto  '),
array('word_id' => '947','n' => '1','meaning' => 'Immediatamente '),
array('word_id' => '948','n' => '1','meaning' => 'Oficina'),
array('word_id' => '95','n' => '1','meaning' => 'Estudiante'),
array('word_id' => '951','n' => '1','meaning' => 'Día 1 (del mes)'),
array('word_id' => '952','n' => '1','meaning' => 'Fijo'),
array('word_id' => '952','n' => '2','meaning' => 'Constante'),
array('word_id' => '952','n' => '3','meaning' => 'Regularizado'),
array('word_id' => '952','n' => '4','meaning' => 'Definido'),
array('word_id' => '953','n' => '1','meaning' => 'Todos juntos'),
array('word_id' => '954','n' => '1','meaning' => 'Zona'),
array('word_id' => '954','n' => '2','meaning' => 'Región'),
array('word_id' => '955','n' => '1','meaning' => 'Febrero'),
array('word_id' => '956','n' => '1','meaning' => '2 personas'),
array('word_id' => '957','n' => '1','meaning' => 'Día 2 (del mes)'),
array('word_id' => '958','n' => '1','meaning' => 'De segunda generación'),
array('word_id' => '959','n' => '1','meaning' => 'Marzo'),
array('word_id' => '96','n' => '1','meaning' => 'Empleado de una compañía (se usa しゃいん cuando va acompañado del nombre de la compañía)'),
array('word_id' => '960','n' => '1','meaning' => 'Día 3 (del mes)'),
array('word_id' => '961','n' => '1','meaning' => 'Una y otra vez'),
array('word_id' => '962','n' => '1','meaning' => 'Abril'),
array('word_id' => '963','n' => '1','meaning' => 'Día 4 (del mes)'),
array('word_id' => '964','n' => '1','meaning' => 'Cruce de caminos'),
array('word_id' => '965','n' => '1','meaning' => 'Mayo'),
array('word_id' => '966','n' => '1','meaning' => 'Día 5 (del mes)'),
array('word_id' => '967','n' => '1','meaning' => 'Olimpiadas'),
array('word_id' => '968','n' => '1','meaning' => 'Pentágono'),
array('word_id' => '969','n' => '1','meaning' => 'Junio'),
array('word_id' => '97','n' => '1','meaning' => 'Australia '),
array('word_id' => '970','n' => '1','meaning' => 'Día 6 (del mes)'),
array('word_id' => '971','n' => '0','meaning' => 'De repente'),
array('word_id' => '972','n' => '1','meaning' => 'Misterioso'),
array('word_id' => '973','n' => '1','meaning' => 'Julio'),
array('word_id' => '974','n' => '1','meaning' => 'Día 7 (del mes)'),
array('word_id' => '975','n' => '1','meaning' => 'Agosto'),
array('word_id' => '976','n' => '1','meaning' => 'Septiembre'),
array('word_id' => '977','n' => '1','meaning' => 'Octubre'),
array('word_id' => '978','n' => '1','meaning' => 'Noviembre'),
array('word_id' => '979','n' => '1','meaning' => 'Diciembre'),
array('word_id' => '98','n' => '1','meaning' => 'Australiano (gentilicio)'),
array('word_id' => '980','n' => '1','meaning' => 'Día 8 (del mes)'),
array('word_id' => '981','n' => '1','meaning' => 'Día 9 (del mes)'),
array('word_id' => '982','n' => '1','meaning' => 'Día 10 (del mes)'),
array('word_id' => '983','n' => '1','meaning' => '1 cosa'),
array('word_id' => '986','n' => '1','meaning' => '3 cosas'),
array('word_id' => '988','n' => '1','meaning' => '4 cosas'),
array('word_id' => '99','n' => '1','meaning' => 'Doctor'),
array('word_id' => '99','n' => '2','meaning' => 'Médico'),
array('word_id' => '990','n' => '1','meaning' => '2 cosas'),
array('word_id' => '991','n' => '1','meaning' => '5 cosas'),
array('word_id' => '992','n' => '1','meaning' => '6 cosas'),
array('word_id' => '993','n' => '1','meaning' => '7 cosas'),
array('word_id' => '994','n' => '1','meaning' => '9 cosas'),
array('word_id' => '995','n' => '1','meaning' => '10 cosas'),
array('word_id' => '996','n' => '1','meaning' => 'Enero'),
array('word_id' => '997','n' => '1','meaning' => 'Destreza'),
array('word_id' => '998','n' => '1','meaning' => 'Especialidad (lo que alguien se le da mejor)'),
array('word_id' => '999','n' => '1','meaning' => 'Verduleria')
        ])->save();
    }
}